(in-package :cl-tls)

(defconstant +fatal+ 2)
(defconstant +warning+ 1)

(defconstant +close-notify+ 0)
(defconstant +unexpected-message+ 10)
(defconstant +bad-record-mac+ 20)
(defconstant +decryption-failed-RESERVED+ 21)
(defconstant +record-overflow+ 22)
(defconstant +decompression-failure+ 30)
(defconstant +handshake-failure+ 40)
(defconstant +no-certificate-RESERVED+ 41)
(defconstant +bad-certificate+ 42)
(defconstant +unsupported-certificate+ 43)
(defconstant +certificate-revoked+ 44)
(defconstant +certificate-expired+ 45)
(defconstant +certificate-unknown+ 46)
(defconstant +illegal-parameter+ 47)
(defconstant +unknown-ca+ 48)
(defconstant +access-denied+ 49)
(defconstant +decode-error+ 50)
(defconstant +decrypt-error+ 51)
(defconstant +export-restriction-RESERVED+ 60)
(defconstant +protocol-version+ 70)
(defconstant +insufficient-security+ 71)
(defconstant +internal-error+ 80)
(defconstant +user-canceled+ 90)
(defconstant +no-renegotiation+ 100)
(defconstant +unsupported-extension+ 110)

(defun send-alert (session level description)
  "Send an alert record"
  (let ((msg (fast-io:make-octet-vector 2)))
    (setf (aref msg 0) (ecase level
			 (:fatal +fatal+) (:warning +warning+)))
    (setf (aref msg 1) (ecase description
			 (:close-notify +close-notify+)
			 (:unexpected-message +unexpected-message+)
			 (:bad-record-mac +bad-record-mac+)
			 (:record-overflow +record-overflow+)
			 (:decompression-failure +decompression-failure+)
			 (:handshake-failure +handshake-failure+)
			 (:bad-certificate +bad-certificate+)
			 (:unsupported-certificate +unsupported-certificate+)
			 (:certificate-revoked +certificate-revoked+)
			 (:certificate-expired +certificate-expired+)
			 (:certificate-unknown +certificate-unknown+)
			 (:illegal-parameter +illegal-parameter+)
			 (:unknown-ca +unknown-ca+)
			 (:access-denied +access-denied+)
			 (:decode-error +decode-error+)
			 (:decrypt-error +decrypt-error+)
			 (:protocol-version +protocol-version+)
			 (:insufficient-security +insufficient-security+)
			 (:internal-error +internal-error+)
			 (:user-canceled +user-canceled+)
			 (:no-renegotiation +no-renegotiation+)
			 (:unsupported-extension +unsupported-extension+)))
    (send session 21 msg)))

(defun alert-record-to-text (content)
  (unless (= 2 (length content))
    (error 'tls-error :text "Invalid ALERT message"))
  (concatenate 'string
	       (case (aref content 0)
		 (2 "Fatal alert: ")
		 (1 "Warning alert: ")
		 (otherwise (error 'tls-error :text "Unknown TLS ALERT level")))
	       (case (aref content 1)
		 (0 "close_notify")
		 (10 "unexpected_message")
		 (20 "bad_record_mac")
		 (21 "decryption_failed_RESERVED")
		 (22 "record_overflow")
		 (30 "decompression_failure")
		 (40 "handshake_failure")
		 (41 "no_certificate_RESERVED")
		 (42 "bad_certificate")
		 (43 "unsupported_certificate")
		 (44 "certificate_revoked")
		 (45 "certificate_expired")
		 (46 "certificate_unknown")
		 (47 "illegal_parameter")
		 (48 "unknown_ca")
		 (49 "access_denied")
		 (50 "decode_error")
		 (51 "decrypt_error")
		 (60 "export_restriction_RESERVED")
		 (70 "protocol_version")
		 (71 "insufficient_security")
		 (80 "internal_error")
		 (90 "user_canceled")
		 (100 "no_renegotiation")
		 (110 "unsupported_extension")
		 (otherwise (error 'tls-error :text "Unknown ALERT description")))))
